spring:
  application:
    name: eureka-consumer-ribbon-hystrix-v2

server:
  port: 2101

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

logging:
  file: ${spring.application.name}.log