spring:
  application:
    name: consul-client
  cloud:
      consul:
        host: localhost
        port: 8500
        discovery:
          healthCheckPath: /
          healthCheckInterval: 5s

server:
  port: 2001
